### ISSUE TITLE
Missing players and missing tiles

### ISSUE THREAD

**Issue by EZWrighter** [ankaraboardgame/ankara#44]
Tried playing on Heroku with 5 players and the fifth player was invisible and only had 12 out of the 16 necessary tiles...missing the fountain.

**Comment by sokmeann** [comment]
@EZWrighter Hello Eric, always great to hear that our game is still being found and played! The max number of player is 4, and yes, there are only 12 of the 16 tiles because this was a 2.5 weeks school project so we chose to drop 4 of the tiles due to time constraints. This repo is not being maintained since 2017, as we all moved on to a bunch of other projects, but feel free to make a PR if you would like to implement the last 4 tiles, I will be happy to review and merge ;-)

**Comment by EZWrighter** [comment]
Looks like you did a nice job.  We didn't actually play since we had 5
people and the game was missing the critical fountain tile 🙂 I might take
a look at your code at some point.
